apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
data:
  elasticsearch.yml: |
    cluster:
      name: ${CLUSTER_NAME}

    node:
      master: ${NODE_MASTER}
      name: ${NODE_NAME}
      data: ${NODE_DATA}
      ingest: ${NODE_INGEST}
    network.host: ${NETWORK_HOST}

    path:
      data: /data/data
      logs: /data/log

    # bootstrap:
    #   memory_lock: true

    http:
      enabled: ${HTTP_ENABLE}
      compression: true

    discovery:
      zen:
        minimum_master_nodes: ${NUMBER_OF_MASTERS}
        ping.unicast.hosts: elasticsearch-discovery.elk.svc.cluster.local
